name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: [3.1, 3.0, 2.7, 2.6, 2.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Lint
      run: bundle exec lefthook run pre-commit
    - name: Test
      run: bundle exec rspec

  benchmark:
    needs: build
    runs-on: ubuntu-latest
    name: Benchmark ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: [3.1, 3.0, 2.7, 2.6, 2.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        working-directory: benchmark
    - name: Run benchmarks
      run: ruby index.rb
      working-directory: benchmark
